### Getting all engineers
GET http://localhost:8080/software-engineers
###

### Create Engineers
POST http://localhost:8080/software-engineers
Content-Type: application/json

{
  "name": "Suresh",
  "techStack": "Java,spring boot",
  "email": "suresh@gmail.com"
}

###

### Update Engineer
PUT http://localhost:8080/software-engineers/52
Content-Type: application/json

{
  "name": "Test123",
  "techStack": "Java,spring boot",
  "email": "test123@gmail.com"
}
###

### Delete Engineers
DELETE http://localhost:8080/software-engineers/52
###